[parse]
    command = './.SpaceVim.d/bin/parse'
    args = ['${wordCopied}', './.SpaceVim.d/tmp/tmp.html']
    description = "快速解析网页"

[fetch]
    command = 'wget'
    args = ["--header='User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'",
            "-O ./.SpaceVim.d/tmp/tmp.html",
            "${wordCopied}"]
    description = "快速获取网页"

